version: 2
jobs:
  build:
    working_directory: ~/PurchasingPlatform/pp-od-inventory
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.3
      environment:
        BUNDLE_JOBS   : 4
        BUNDLE_RETRY  : 3
        BUNDLE_PATH   : vendor/bundle
        RAILS_ENV     : test
        RACK_ENV      : test

    steps:
    - run: 'echo ''Etc/UTC'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure
          -f noninteractive tzdata; '
    - checkout

    - run: echo `ruby -v`
    - run: echo `gem -v`
    - run: echo `bundle -v`

    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-

    - run: 'bundle check || bundle install'

    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./vendor/bundle

    - run: bundle exec rspec


